---
- hosts: k8s-control-plane:k8s-worker
  become: true
  tasks:
  - name: Ensure dependencies are installed.
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - gnupg2
        - curl
        - software-properties-common
      state: present
  - name: Configure persistent loading on containerd modules
    copy:
      dest: /etc/modules-load.d/containerd.conf
      content: |
        overlay
        br_netfilter
  - name: Sysctl reload
    shell: "sysctl --system"

  - name: Add Docker apt key.
    apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_repository_key
    ignore_errors: true

  - name: Add Docker repository.
    apt_repository:
      repo: "deb [arch={{ (ansible_architecture == \"aarch64\") | ternary(\"arm64\", \"amd64\") }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: true

  - name: Ensure containerd is installed.
    package:
      name: "containerd.io"
      state: "present"
