---
- hosts: k8s-control-plane:k8s-worker
  become: true
  tasks:

  - name: Init kubeadm
    shell: |
      kubeadm init
    register: init_cluster
    environment:
      no_proxy: "$no_proxy,.svc,.svc.cluster.local"
  - debug:
      var: init_cluster
